### ISSUE TITLE
Class extends value [object Object] is not a constructor or null

### ISSUE THREAD

**Issue by sameer-hashflow** [isaacs/minipass#51]
Hello! I am using a package which uses minipass via `tar`->`minizlib`. When I try to import it I get this error:

```
    TypeError: Class extends value [object Object] is not a constructor or null
```

The stack trace points to minizlib/index.js:192 which is a class which inherits from `Minipass`

```
      at Object.<anonymous> (../node_modules/minizlib/index.js:192:4)
      at Object.<anonymous> (../node_modules/tar/lib/pack.js:26:14)
      at Object.<anonymous> (../node_modules/tar/lib/create.js:6:14)
      at Object.<anonymous> (../node_modules/tar/index.js:4:30)
      at Object.<anonymous> (../node_modules/redis-memory-server/src/util/RedisBinaryDownload.ts:7:1)
      at Object.<anonymous> (../node_modules/redis-memory-server/src/util/RedisBinary.ts:9:1)
      at Object.<anonymous> (../node_modules/redis-memory-server/src/index.ts:3:1)
```

I filed this issue with `redis-memory-server` which has a repro uploaded.

https://github.com/mhassan1/redis-memory-server/issues/18

**Comment by mhassan1** [comment]
The reproduction seems to be related to resolving the wrong version of `minipass` due to the presence of [`moduleDirectories`](https://jestjs.io/docs/configuration#moduledirectories-arraystring) in the Jest configuration. I think this issue can be closed.

**Comment by sameer-hashflow** [comment]
Thanks! Appreciate your help with this. I was able to modify the jest config of my main codebase as well to get it to work.
